replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/terraform-project-namazsari/artemis/artemis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "3.0.0"

ingress:
  enabled: true
  annotations:
    ngress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: prod.ozzynsari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-prod-tls
      hosts:
        - prod.ozzynsari.com