replicaCount: 3



ingress:
  enabled: true
  annotations:
    ngress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: dev.ozzynsari.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-dev-tls
      hosts:
        - dev.ozzynsari.com